### ISSUE TITLE
Distributed Training Error

### ISSUE THREAD

**Issue by CYYJL** [DIYer22/discrete_distribution_networks#1]
Hi，When I try to train with multiple GPUs, I encounter a Rank timeout error. However, if I set --nproc_per_node=1, the code runs normally without any issue. My Environment is : torch 2.3.1，cuda 11.8，python 3.10 ，NCCL   2.18.3

<img width="1502" height="621" alt="Image" src="https://github.com/user-attachments/assets/03547c65-b5a2-482f-a7b5-08202fc6cf4f" />

**Comment by DIYer22** [comment]
It's strange that the default training setup in the README, the resume_pkl is False, which doesn't call this function `misc.copy_params_and_buffers` 

I double-checked it with Claude. Is your command the default training command?

----
> if only run default train cmd in readme, will it call misc.copy_params_and_buffers funcation?

**Answer: No.**

When you run the default training command in the README:

```bash
torchrun --standalone --nproc_per_node=8 train.py --data datasets/cifar10-32x32.zip \
  --outdir training-runs --batch-gpu=256 --batch=2048 --desc=task_name \
  --max-blockn=32 --chain-dropout=0.05 --max-outputk=64
```

the function `misc.copy_params_and_buffers` **will not** be called. Here's why:

1. **Default argument values**: In `training_loop.py`, the function signature shows:
   - `resume_pkl=None` (default)
   - `resume_state_dump=None` (default)

2. **Call conditions**: `misc.copy_params_and_buffers` is invoked only when:
   - `resume_pkl is not None` (lines 140–150)
   - `resume_state_dump is not None` (lines 151–156)

3. **Default training command**: The command does **not** specify:
   - `--resume` (used to resume from a previous checkpoint)
   - `--transfer` (used for transfer-learning)

4. **Logic in train.py**: Lines 465–490 in `train.py` reveal that `c.resume_pkl` and `c.resume_state_dump` are set **only** when the user explicitly supplies `--resume` or `--transfer`.

Hence, with the default training command both parameters remain `None`, and `misc.copy_params_and_buffers` is never executed; it is triggered solely when resuming training or performing transfer learning.

**Comment by CYYJL** [comment]
Hi, I trained the model using your default settings. After some adjustments and debugging, I found that the issue was caused by the following line in `training_loop.py` :
`ddp = torch.nn.parallel.DistributedDataParallel(
    net, device_ids=[device], broadcast_buffers=False
)`
It seems this line may cause problems when mapping GPUs. I modified it as follows (based on a related [issue](https://github.com/NVlabs/edm/issues/18)), and it worked:
`ddp = torch.nn.parallel.DistributedDataParallel(
    net, device_ids=[dist.get_rank()], broadcast_buffers=False
)`
In addition, I used PCIe communication to accelerate the distributed training. P2P communication seems more prone to problems. You can disable P2P and switch to PCIe by setting the following environment variables:
`export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_DEBUG=INFO
export NCCL_BLOCKING_WAIT=1`
